/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:773fa913-b582-4f1e-909f-7e2d140071b4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_izDtJY34t",
    "aws_user_pools_web_client_id": "77js489e8eimv883es99grkrce",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://vek5khysi5a6hfvv6fqmetbesy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5x4lfd2mr5ff3k5pxspnm466ta",
    "aws_user_files_s3_bucket": "volunteersignup4a866ba665444e18bed19983888f579660028-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
